### ISSUE TITLE
Signs doesn't seem to work

### ISSUE THREAD

**Issue by MythixDino** [KaiKikuchi/GPPRealEstate#5]
When I try to create a sign in a claim, they don't do anything. Also the commands doesn't seem to work. It always says 'I don't know what to do with that'

Can you please help?

**Comment by KaiKikuchi** [comment]
You need to provide more info about your server. A complete startup server log will help.

**Comment by MythixDino** [comment]
Here is a log of the server startup (Didn't copy the FML startup)
http://pastebin.com/6LmDAeR3
However I found an error when trying to create a sign:
[18:23:18] [Server thread/INFO] [Minecraft/]: [GriefPreventionPlus] Mythixdino placed at world: x4964, z5168 this sign: 
 [RE] selling 20
[18:23:18] [Server thread/ERROR] [Minecraft/]: Could not pass event SignChangeEvent to GPPRealEstate v0.9.6
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.175]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.175]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.175]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.175]
	at net.minecraft.network.NetHandlerPlayServer.func_147343_a(NetHandlerPlayServer.java:2294) [nh.class:?]
	at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:48) [jn.class:?]
	at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:9) [jn.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
Caused by: java.lang.NoSuchMethodError: net.kaikk.mc.gpp.GriefPreventionPlus.getInstance()Lnet/kaikk/mc/gpp/GriefPreventionPlus;
	at net.kaikk.mc.gpprealestate.EventListener.onSignChange(EventListener.java:77) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.175]
	... 13 more
Server information:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.175
	Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
	Java Version: 1.8.0_66-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 242273192 bytes (231 MB) / 2271068160 bytes (2165 MB) up to 4233953280 bytes (4037 MB)
	JVM Flags: 12 total; -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=7 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:+UseConcMarkSweepGC -XX:+AggressiveOpts -Xmx4096M -Xms1024M -XX:PermSize=256m -XX:MaxPermSize=1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 244 mods loaded, 244 mods active

Hope this helps.

**Comment by KaiKikuchi** [comment]
You're using a very old version of GPP and ForgeRestrictor.

**Comment by MythixDino** [comment]
Which versions are the last supported for 1.7.10?

**Comment by KaiKikuchi** [comment]
latest versions of both GPP and fres
